.PHONY: init-dev
# Init environment for development.
init-dev:
	@pip install --upgrade pip && \
	pip install --requirement requirements.txt && \
	pre-commit install

.PHONY: homework-i-run
# Run homework.
homework-i-run:
	@make migrate && \
	python manage.py runserver

.PHONY: homework-i-purge
homework-i-purge:
	@echo Goodbye

.PHONY: pre-commit-run
# Run tools for files from commit.
pre-commit-run:
	@pre-commit run

.PHONY: pre-commit-run-all
# Run tools for all files.
pre-commit-run-all:
	@pre-commit run --all-files


.PHONY: d-homework-i-run
# Make all actions needed for run homework from zero.
d-homework-i-run:
	@make d-run

.PHONY: d-homework-i-purge
# Make all actions needed for purge homework related data.
d-homework-i-purge:
	@make d-purge

.PHONY: d-run
# Just run
d-run:
  @python manage.py migrate && \
	COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 \
		docker compose up --build

.PHONY: d-stop
# Stop services
d-stop:
	@COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 \
		docker compose down

.PHONY: d-purge
# Purge all data related with services
d-purge:
	@COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 \
		docker compose down --volumes --remove-orphans --rmi local --timeout 0


.PHONY: migrations
# Make migrations
migrations:
	@python manage.py makemigrations

.PHONY: migrate
# Migrate
migrate:
	@python manage.py migrate


.PHONY: django-i-generate-contacts-i-100
# Generate 100 phone_book
django-i-generate-contacts-i-100:
	@python manage.py generate_contacts --amount 100

.PHONY: django-i-delete-contacts-is-only-autogenerated
# Delete all phone_book is only auto generated
django-i-delete-contacts-is-only-autogenerated:
	@python manage.py delete_contacts --is-only-auto-generated


.PHONY: init-dev-i-create-superuser
# Create standard superuser
init-dev-i-create-superuser:
	@python manage.py create_superuser

.PHONY: init-dev-i-delete-superuser
# Delete superuser
init-dev-i-delete-superuser:
	@python manage.py delete_superuser