# Generated by Django 4.1.7 on 2023-03-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to="contacts/contact/avatar/"),
        ),
    ]
