# Generated by Django 4.1.7 on 2023-03-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("middleware_requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="httprequestslog",
            name="created_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
